---

- name: Stop Tomcat
  service: name=tomcat state=stopped 

- name: Clean up the project
  command: /usr/bin/mvn clean
  args:
    chdir: /project
    
- name: Building workflow project
  command: /usr/bin/mvn install -DskipTests
  args:
    chdir: /project

- name: copy application to webapp directory
  command: cp /project/wf-dniprorada/target/wf-dniprorada.war /usr/share/tomcat/webapps/wf-dniprorada.war

- name: Start Tomcat
  service: name=tomcat state=started enabled=yes

- name: wait for tomcat to start
  wait_for: port={{http_port}}
